ALPHA_VANTAGE_API_KEY = "BN3UF29VKSR67YHN"
ALPACA_API_KEY = "PKB3GME4Y837WW3HQS00"
ALPACA_END_POINT = "https://paper-api.alpaca.markets/"
ALPACA_SECRET_KEY = "TuFcUldn4HmBjPocR7cUH9SudJQvlCQwf0uXvKxg"
