name: CI/CD → Docker Hub & EC2 (manual Docker)

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Build image
        run: docker build -t "${{ secrets.DOCKERHUB_USER }}/ststockprediction1:latest" .

      - name: Push image
        run: docker push "${{ secrets.DOCKERHUB_USER }}/ststockprediction1:latest"

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: SSH & pull+run
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USER }}/ststockprediction1:latest
            docker rm -f ststockprediction1 || true
            docker run -d \
              --name ststockprediction1 \
              --restart=always \
              -p 8501:8501 \
              -e ALPHA_VANTAGE_API_KEY=${{ secrets.ALPHA_VANTAGE_API_KEY }} \
              ${{ secrets.DOCKERHUB_USER }}/ststockprediction1:latest
